name: checkout-commit-push
on:
  workflow_dispatch:
jobs:
  checkout-commit-push:
    name: Checkout, Commit and Push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Add new report
        run: |
          folder=$(date +%s)
          date > "reports/$folder"

      - name: Commit and Push
        run: |
          message="Report generated at $(date +%s)"
          git checkout -b feat/new-report
          git config push.autoSetupRemote true
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports/
          git commit -m "$message"
          git push
      
      - name: Create a PR
        id: pr-create
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "pull_request_url=$(gh pr create -B main -t \"New Report\" -b \"Adding a new report automatically generated.
          $(date +%s) 
          \")" >> "$GITHUB_OUTPUT"
          
      - name: Send GitHub Action trigger data to Slack workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        id: slack
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "job_status": "${{ job.status }}",
              "job_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "pull_request_url": "${{ steps.pr-create.outputs.pull_request_url }}",
              "commit_url": "${{ github.event.head_commit.url }}"
            }
