name: checkout-commit-push
on:
  workflow_dispatch:
jobs:
  build:
    name: Checkout, Commit and Push
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Add new report
        run: |
          folder=$(date +%s)
          date > "reports/$folder"

      - name: Commit and Push
        run: |
          message="Report generated at $(date +%s)"
          git config user.name GitHub Actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add reports/
          git commit -m "$message"
          git push

      
